[versions]
kotlin = "1.9.24"
spring = "6.1.9"
springboot = "3.3.0"
springdoc = "2.5.0"

[libraries]
detekt-formatting = "io.gitlab.arturbosch.detekt:detekt-formatting:1.23.6"
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

jakarta-xml-bind-api = "jakarta.xml.bind:jakarta.xml.bind-api:4.0.2"
jooq = { module = "org.jooq:jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen" }
jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
liquibase-core = { module = "org.liquibase:liquibase-core" }
mockserver = { module = "org.testcontainers:mockserver" }
mockserver-client-java = "org.mock-server:mockserver-client-java:5.15.0"
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.3.1"
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springboot" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springboot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-jooq = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-mail = { module = "org.springframework.boot:spring-boot-starter-mail" }
spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "spring" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-webflux = { module = "org.springframework:spring-webflux" }
springdoc-openapi-kotlin = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "springdoc" }
springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.19.8"
archunit = "com.tngtech.archunit:archunit-junit5:1.3.0"
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose", version.ref = "springboot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springboot" }
org-testcontainers-postgresql = { module = "org.testcontainers:postgresql" }
postgresql = "org.postgresql:postgresql:42.7.3"
jsonwebtoken = "io.jsonwebtoken:jjwt-api:0.12.5"
jsonwebtoken-impl = "io.jsonwebtoken:jjwt-impl:0.12.5"
jsonwebtoken-orgjson = "io.jsonwebtoken:jjwt-orgjson:0.12.5"

[plugins]
detekt = "io.gitlab.arturbosch.detekt:1.23.6"
diktat = "com.saveourtool.diktat:2.0.0"
jooq = "nu.studer.jooq:8.2.3"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
springframework-boot = { id = "org.springframework.boot", version.ref = "springboot" }
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.4"
sonarqube = "org.sonarqube:4.3.1.3277"
versions = "com.github.ben-manes.versions:0.51.0"
gitproperties = "com.gorylenko.gradle-git-properties:2.4.2"
